# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d730291d2f9929aafb10cdd6e9056267ed7296730dbf66b204bec71eaf1831a18cb186352137affe69cb966133fff466b8095393a34419e8706fc23c25b450a0

test:
  secret_key_base: 109ea13f8e61cb97d71800e97526c3a5225cd994f2576417d49efa22c37f9c179289a245c3ff8bd56bc1c1abe330f711eee7510f7035f83732d950723f387dbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
